[default]
access_key = 6440fa09f1d11daf181f602cf5c4cd3b98c9f1bb_elixir-europe.org  # Change with your ELIXIR ID / LS-AAI
secret_key = 6440fa09f1d11daf181f602cf5c4cd3b98c9f1bb_elixir-europe.org  # Change with your ELIXIR ID / LS-AAI
access_token=eyJr... [LONG STRING, TRUNCATED]  # Change with your Access Token from https://auth.dev.gdi.lu/
check_ssl_certificate = False
check_ssl_hostname = False
encoding = UTF-8
encrypt = False
guess_mime_type = True
host_base = localhost:8000
host_bucket = localhost:8000
human_readable_sizes = true
multipart_chunk_size_mb = 50
use_https = False
socket_timeout = 30