
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8800:80"
      - "4433:443"
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - beacon-priv
      - htsget-priv
      - rems-priv 
      - auth-priv
      - download-priv
      - s3inbox-priv
    restart: unless-stopped

networks:
  beacon-priv:
    name: beacon-priv 
  htsget-priv:
    name: htsget-priv
  rems-priv:
    name: rems-priv
  auth-priv:
    name: auth-priv
  download-priv:
    name: download-priv
  s3inbox-priv:
    name: s3inbox-priv
  