
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8800:80"
      - "4433:443"
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - beacon-priv
      - htsget-priv
      - rems-priv 
    restart: unless-stopped

networks:
  beacon-priv:
    name: beacon-priv 
  htsget-priv:
    name: htsget-priv
  rems-priv:
    name: rems-priv