app: # this is for download
  host: "0.0.0.0"
  port: "8443"
  servercert: /shared/cert/fullchain.pem
  serverkey: /shared/cert/privkey.pem

archive:
  type: "s3"
  url: "http://s3"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "archive"
  chunksize: 32

aws:
  url: "http://s3:9000"
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretkey"
  bucket: "inbox"
  region: "us-east-1"

broker:
  host: "rabbitmq"
  port: 5672
  user: ""
  password: ""
  vhost: "gdi"
  queue: ""
  exchange: "sda"
  routingKey: ""
  routingError: "error"
  ssl: "false"

c4gh:
  passphrase: "c4ghpass"
  filepath: "/shared/c4gh.sec.pem"
  backupPubKey: "/shared/c4gh.pub.pem"

db:
  host: "postgres"
  port: 5432
  user: ""
  password: ""
  database: "lega"
  sslmode: "disable"

inbox:
  type: "s3"
  url: "http://s3"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "inbox"
  chunksize: 32

log:
  level: "debug"
  format: "json"

oidc:
  # oidc configuration API must have values for "userinfo_endpoint" and "jwks_uri"
  #cacert: "/shared/cert/ca.crt"
  configuration:
    url: "https://login.elixir-czech.org/oidc/.well-known/openid-configuration"
  trusted:
    iss: "/iss.json"

schema:
  type: isolated

server:
  jwtpubkeypath: "/shared/keys/pub/"
  jwtpubkeyurl: ""

session:
  # session key expiration time in seconds
  # default value = -1 for disabled state
  # a positive integer enables sessions
  # a negative integer disables sessions
  expiration: 28800
  # domain name must be set to the hostname (FQDN) of the service
  domain: "localhost"
  # session cookie Secure value, if true, TLS must be active
  # default value = true
  secure: true
  # session cookie HttpOnly value, if true, TLS must be active
  # default value = true
  httponly: true
  # name of session cookie
  # default value = sda_session_key
  name: "sda_session_key"